### PR TITLE
Update pipeline.yml

### PR DESCRIPTION
**Pull request by valentina-s**
push test_CI

### CODE REVIEW

**Comment by Benjamintdk** [comment]
@valentina-s I experimented with using the `gh-pages -d dist` command on the master branch recently as well, but it keeps failing, not sure of what exactly the issue is. Seems like most people online use a [third party action](https://github.com/marketplace/actions/deploy-to-github-pages) to deploy to github pages. I tested it recently and it seems to work, was thinking that this could be an interim measure first. Have updated my PR with [it](https://github.com/Benjamintdk/orcaal/blob/2c9079c38754a4965ed3e4c93f308e6dd3736cc5/.github/workflows/pipeline.yml#L82).

**Comment by Benjamintdk** [comment]
Forgot to mention as well that I [downgraded](https://github.com/Benjamintdk/orcaal/commit/2c9079c38754a4965ed3e4c93f308e6dd3736cc5) the version of the tagging action from 1.38 to 1.36 because of the error, seems like a [recent issue](https://github.com/anothrNick/github-tag-action/issues/135). Not entirely comfortable relying on 3rd party actions but something we can discuss moving forward as well I think.

**Comment by valentina-s** [comment]
Great, seems everything is  working with your updates! I will merge. You can add an issue to remind us to investigate the gh-pages function, and switch away from the 3rd party one in the future.

**Comment by Benjamintdk** [comment]
Thanks so much Valentina! Have added the issue already. Also, if I make future PRs relating to improving the workflows, do I open the PR to the test_CI branch instead?

**Pull request closed without merging**
